### ISSUE TITLE
Javascript TypeError on FireFox

### ISSUE THREAD

**Issue by sjkelly** [rohitvarkey/ThreeJS.jl#13]
I am still getting accustom to Javascript debugging, so please excuse the sparse report. This is with the script in #12. I see the following error:

```
TypeError: Polymer.dom(...).parentNode.addVertex is not a function
```

From what I can tell this is since it is being called to `THREE.Color`. I also notice a few more, which from what I can tell might be caused by the DOM object being sorted.

![screenshot from 2015-10-06 20 53 18](https://cloud.githubusercontent.com/assets/2086412/10326713/6b66c6b6-6c6c-11e5-92da-fed3f21c5964.png)

I believe this is why rendering a mesh is a hit-or-miss. Into the Escher/Patchwork/ThreeJS rabbit hole :).

**Comment by rohitvarkey** [comment]
Hmm. I kept getting the same in IJulia too. I use Chrome mostly and didn't test this in Firefox! 

The reason is that Polymer doesn't do its job really well here. This occurs because the parent element (`three-js-geometry`) isn't totally ready when I try to add the vertices and the faces to it. Adding a delay to the async operation did fix it for me.

Can you try and see if https://github.com/rohitvarkey/ThreeJS.jl/commit/b327a0e6ef3d0b9267af9da9fbc746c67d710298 fixes it for you?

**Comment by sjkelly** [comment]
b327a0e doesn't fix on Firefox unfortunately, but Chromium works fine. Your diagnosis is very helpful, I will keep looking into it.

**Comment by rohitvarkey** [comment]
@sjkelly Can you check this on the current `master`? I've changed the internals so hopefully this doesn't happen anymore.

**Comment by sjkelly** [comment]
Great! This is no longer an issue on Firefox or Chromium.
